<?php

namespace Ignite\Finance\Database\Seeders;

use Ignite\Finance\Entities\FinanceSmartExchangeFiles;
use Illuminate\Database\Seeder;

class SmartInterfaceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->getFiles() as $files) {
            FinanceSmartExchangeFiles::create($files);
        }
    }

    private function getFiles()
    {
        return [
            ['Global_ID' => 'KE000000000000000000000000001302891', 'Member_Nr' => '11034492', 'Admit_ID' => '745703', 'Progress_Flag' => '0', 'Rejection_Reason' => NULL, 'Exchange_Type' => '1', 'InOut_Type' => '1', 'Location_ID' => '1', 'Smart_Date' => '2015-10-30 07:08:14', 'Smart_File' => '<AdmissionInformation><Admit_Notes></Admit_Notes><PaymentModifiers><PaymentModifier><Type>0</Type><Amount_Required>0</Amount_Required><Receipt></Receipt></PaymentModifier><PaymentModifier><Type>5</Type><NHIF_Member_Nr>ACTIVE</NHIF_Member_Nr><NHIF_Contributor_Nr></NHIF_Contributor_Nr><NHIF_Employer_Code></NHIF_Employer_Code><NHIF_Site_Nr>0</NHIF_Site_Nr><NHIF_Patient_Relation>Self</NHIF_Patient_Relation><Diagnosis_Code></Diagnosis_Code><Admit_Date>10/30/2015 7:14:50 AM</Admit_Date><Discharge_Date></Discharge_Date><Days_Used></Days_Used><Amount></Amount></PaymentModifier></PaymentModifiers><A1><card_retmasscounter>0</card_retmasscounter><card_issuedate>2015-08-20</card_issuedate><card_issuername>SMART KENYA</card_issuername><card_serialnumber>000000100013E0F4</card_serialnumber><card_validitystatus>1</card_validitystatus><card_retcounter>2</card_retcounter></A1><A2><patient_marriagestatus></patient_marriagestatus><policy_country>KE</policy_country><patient_surname>OCHOLA</patient_surname><patient_partnerprevioussurname></patient_partnerprevioussurname><patient_previoussurname></patient_previoussurname><patient_marriagedate>1899-12-31</patient_marriagedate><patient_partnerdob>1899-12-31</patient_partnerdob><patient_forenames>JOSEPH ODERO OCHOLA</patient_forenames><patient_dob>1965-02-07</patient_dob><patient_title></patient_title><policy_currency>404</policy_currency><policy_id>17997</policy_id><patient_language></patient_language></A2><A3><patient_address></patient_address><employer_fax></employer_fax><employer_cellphone></employer_cellphone><employer_telephone></employer_telephone><patient_cellphone></patient_cellphone><patient_email></patient_email><employer_name></employer_name><employer_address>NUMERICAL MACHINING COMPLEX LIMITED</employer_address><employer_department>0000</employer_department><patient_telephone></patient_telephone></A3><A4><patient_id></patient_id><patient_birthcountry></patient_birthcountry><patient_passportnumber></patient_passportnumber><patient_division></patient_division><patient_location></patient_location><patient_birthprovince></patient_birthprovince><patient_idissuedate>1899-12-31</patient_idissuedate><patient_passportexpirydate>1899-12-31</patient_passportexpirydate><patient_birthcity></patient_birthcity><patient_subdivision></patient_subdivision><patient_idcountry></patient_idcountry><patient_passportapplicationdate>1899-12-31</patient_passportapplicationdate><patient_passportcountry></patient_passportcountry><patient_passportissuedate>1899-12-31</patient_passportissuedate><patient_passportcity></patient_passportcity><patient_sublocation></patient_sublocation></A4><A5><patient_gender>1</patient_gender><patient_minutia_identifier>0</patient_minutia_identifier><patient_height>0</patient_height></A5><A6><patient_nextofkin></patient_nextofkin><patient_nextofkin_nr></patient_nextofkin_nr><patient_organdonor>False</patient_organdonor><patient_livingwill>False</patient_livingwill><patient_allergies></patient_allergies><patient_bloodtype></patient_bloodtype><patient_chronicmedication></patient_chronicmedication><patient_chronicconditions></patient_chronicconditions></A6><A7 /><A8><patient_riskfactors></patient_riskfactors></A8><B1><medicalaid_expiry>2016-07-31</medicalaid_expiry><medicalaid_rules>0</medicalaid_rules><medicalaid_showpools>True</medicalaid_showpools><medicalaid_plan>NMLB</medicalaid_plan><medicalaid_limit>0</medicalaid_limit><medicalaid_number>KEHR02235152-00</medicalaid_number><medicalaid_groupstatus></medicalaid_groupstatus><nhif_membernumber>ACTIVE</nhif_membernumber><medicalaid_regdate>2015-08-01</medicalaid_regdate><global_id>KE000000000000000000000000001302891</global_id><medicalaid_code>HR</medicalaid_code><dependant_number>00</dependant_number></B1><B2><bt_sequencenr>0</bt_sequencenr><dr_name></dr_name><dr_surgeryaddress></dr_surgeryaddress><dr_practiceemail></dr_practiceemail><dr_surname></dr_surname><dr_title></dr_title><dr_practicenumber></dr_practicenumber><dr_practiceipanumber></dr_practiceipanumber><dr_practicetelephone></dr_practicetelephone></B2><B4 /><B5><drtemplate_code></drtemplate_code><drtemplate_flags>00000000000000000000000000000000000</drtemplate_flags><drtemplate_enddate>1899-12-31</drtemplate_enddate><drtemplate_startdate>1899-12-31</drtemplate_startdate><drtemplate_practicenumber></drtemplate_practicenumber></B5><E6 /><NonMemMap><card_claimingreason></card_claimingreason><card_reterrors>False</card_reterrors><switch_integrated>False</switch_integrated><supervisor_password></supervisor_password><card_claimfilesloading>False</card_claimfilesloading><card_retcompleted>True</card_retcompleted><card_claimingpossible>True</card_claimingpossible><code_file_version>1</code_file_version><medicalaid_scheme></medicalaid_scheme><btupdate_completed>False</btupdate_completed><patient_hospitalnumber>11034492</patient_hospitalnumber><virtualcard>False</virtualcard></NonMemMap><RepeatableVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>10</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination></RepeatableVaccinations><B6><Message><Nr>1</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>2</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>3</Nr><Date>1899-12-31</Date><Text></Text></Message></B6><Scripts><Script><Nr>1</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>2</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>3</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script></Scripts><Benefits><Benefit><Nr>1</Nr><Description>OUTPATIENT SERVICES CONSULTATION / LABARATORY / PATHOLOGY / XRAY</Description><Amount>94333.52</Amount><PreAuthNeeded>False</PreAuthNeeded><Claimable>True</Claimable></Benefit></Benefits><OnceOffVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name>Birth-BCG &amp; Polio</Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name>6w-DTacP-Hib, DPT</Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name>10w-DPT,Polio,H Influenza,Hepatitis B</Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name>14w-DPT,Polio,H Influenza &amp; Hepatitis B</Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name>9m-Measles</Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-Measles</Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-MMR</Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name>18m-DPT,Polio,H Influenza,Hep A</Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name>5yr-DT,Polio &amp; MMR</Name></Vaccination></OnceOffVaccinations></AdmissionInformation>', 'Exchange_Date' => '2015-10-30 07:09:09', 'Exchange_File' => '<Claim>
			<Claim_Header>
				<Invoice_Number>PDRC140646422</Invoice_Number>
				<Claim_Date>2015-10-30</Claim_Date>
				<Claim_Time>07:09:46</Claim_Time>
				<Pool_Number>1</Pool_Number>
				<Total_Services>0</Total_Services>
				<Gross_Amount>7384</Gross_Amount>
				<Provider>
				<Role>SP</Role>
				<Country_Code>KEN</Country_Code>
				<Group_Practice_Number>SKSP_92</Group_Practice_Number>
				<Group_Practice_Name>The Mater Hospital</Group_Practice_Name>
				</Provider>
				<Authorization>
				<Pre_Authorization_Number>0</Pre_Authorization_Number>
				<Pre_Authorization_Amount>0</Pre_Authorization_Amount>
				</Authorization>
				<Payment_Modifiers>
					<Payment_Modifier>
						<Type>1</Type>
						<Amount>0</Amount>
						<Receipt>0</Receipt>
					</Payment_Modifier>
					<PaymentModifier>
						<Type>5</Type>
						<NHIF_Member_Nr>0</NHIF_Member_Nr>
						<NHIF_Contributor_Nr>0</NHIF_Contributor_Nr>
						<NHIF_Employer_Code>0</NHIF_Employer_Code>
						<NHIF_Site_Nr>0</NHIF_Site_Nr>
						<NHIF_Patient_Relation>0</NHIF_Patient_Relation>
						<Diagnosis_Code>0</Diagnosis_Code>
						<Admit_Date>2015-10-30</Admit_Date>
						<Discharge_Date>2015-10-30</Discharge_Date>
						<Days_Used>0</Days_Used>
						<Amount>0</Amount>
					</PaymentModifier>
				</Payment_Modifiers>
			</Claim_Header>
			<Member>
				<Membership_Number>02235152-00</Membership_Number>
				<card_serialnumber>000000100013E0F4</card_serialnumber>
				<Scheme_Code>unknown</Scheme_Code>
				<Scheme_Plan>unknown</Scheme_Plan>
			</Member>
			<Patient>
				<Dependant>Y</Dependant>
				<First_Name>JOSEPH</First_Name>
				<Middle_Name>ODERO</Middle_Name>
				<Surname>OCHOLA</Surname>
				<Date_Of_Birth>1965-02-07</Date_Of_Birth>
				<Gender>M</Gender>
			</Patient>
			<Claim_Data>
				<Discharge_Notes>Diagn</Discharge_Notes><Service>
							<Number>1</Number>
							<Invoice_Number>PDRC140646422</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-30</Start_Date>
							<Start_Time>07:09:46</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Medication</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>A234</Code>
							<Code_Description>ATRIPLA TABLETS</Code_Description>
							<Quantity>30</Quantity>
							<Total_Amount>7383.3</Total_Amount>
							<Reason></Reason>
						</Service></Claim_Data>
			</Claim>', 'Result_Date' => '0000-00-00 00:00:00', 'Result_File' => ''],
            ['Global_ID' => 'KE000000000000000000000000000728751', 'Member_Nr' => '11007503', 'Admit_ID' => '745701', 'Progress_Flag' => '0', 'Rejection_Reason' => NULL, 'Exchange_Type' => '1', 'InOut_Type' => '1', 'Location_ID' => '2', 'Smart_Date' => '2015-10-30 07:03:07', 'Smart_File' => '<AdmissionInformation><Admit_Notes></Admit_Notes><PaymentModifiers><PaymentModifier><Type>0</Type><Amount_Required>0</Amount_Required><Receipt></Receipt></PaymentModifier><PaymentModifier><Type>5</Type><NHIF_Member_Nr>ACTIVE</NHIF_Member_Nr><NHIF_Contributor_Nr></NHIF_Contributor_Nr><NHIF_Employer_Code></NHIF_Employer_Code><NHIF_Site_Nr>0</NHIF_Site_Nr><NHIF_Patient_Relation>Self</NHIF_Patient_Relation><Diagnosis_Code></Diagnosis_Code><Admit_Date>10/30/2015 7:02:41 AM</Admit_Date><Discharge_Date></Discharge_Date><Days_Used></Days_Used><Amount></Amount></PaymentModifier></PaymentModifiers><A1><card_retmasscounter>0</card_retmasscounter><card_issuedate>2014-01-07</card_issuedate><card_issuername>SMART KENYA</card_issuername><card_serialnumber>000000100006DA3C</card_serialnumber><card_validitystatus>1</card_validitystatus><card_retcounter>2</card_retcounter></A1><A2><patient_marriagestatus></patient_marriagestatus><policy_country>KE</policy_country><patient_surname>KUTTO</patient_surname><patient_partnerprevioussurname></patient_partnerprevioussurname><patient_previoussurname></patient_previoussurname><patient_marriagedate>1899-12-31</patient_marriagedate><patient_partnerdob>1899-12-31</patient_partnerdob><patient_forenames>RODNEY KIMUTAI KUTTO</patient_forenames><patient_dob>2005-12-02</patient_dob><patient_title></patient_title><policy_currency>404</policy_currency><policy_id>4538</policy_id><patient_language></patient_language></A2><A3><patient_address></patient_address><employer_fax></employer_fax><employer_cellphone></employer_cellphone><employer_telephone></employer_telephone><patient_cellphone></patient_cellphone><patient_email></patient_email><employer_name></employer_name><employer_address></employer_address><employer_department>0000</employer_department><patient_telephone></patient_telephone></A3><A4><patient_id></patient_id><patient_birthcountry></patient_birthcountry><patient_passportnumber>111471</patient_passportnumber><patient_division></patient_division><patient_location></patient_location><patient_birthprovince></patient_birthprovince><patient_idissuedate>1899-12-31</patient_idissuedate><patient_passportexpirydate>1899-12-31</patient_passportexpirydate><patient_birthcity></patient_birthcity><patient_subdivision></patient_subdivision><patient_idcountry></patient_idcountry><patient_passportapplicationdate>1899-12-31</patient_passportapplicationdate><patient_passportcountry></patient_passportcountry><patient_passportissuedate>1899-12-31</patient_passportissuedate><patient_passportcity></patient_passportcity><patient_sublocation></patient_sublocation></A4><A5><patient_gender>0</patient_gender><patient_minutia_identifier>0</patient_minutia_identifier><patient_height>0</patient_height></A5><A6><patient_nextofkin></patient_nextofkin><patient_nextofkin_nr></patient_nextofkin_nr><patient_organdonor>False</patient_organdonor><patient_livingwill>False</patient_livingwill><patient_allergies></patient_allergies><patient_bloodtype></patient_bloodtype><patient_chronicmedication></patient_chronicmedication><patient_chronicconditions></patient_chronicconditions></A6><A7 /><A8><patient_riskfactors></patient_riskfactors></A8><B1><medicalaid_expiry>2014-12-31</medicalaid_expiry><medicalaid_rules>0</medicalaid_rules><medicalaid_showpools>True</medicalaid_showpools><medicalaid_plan>BAYERPF</medicalaid_plan><medicalaid_limit>0</medicalaid_limit><medicalaid_number>8761108-04</medicalaid_number><medicalaid_groupstatus></medicalaid_groupstatus><nhif_membernumber>ACTIVE</nhif_membernumber><medicalaid_regdate>1899-12-31</medicalaid_regdate><global_id>KE000000000000000000000000000728751</global_id><medicalaid_code>UAP</medicalaid_code><dependant_number>00</dependant_number></B1><B2><bt_sequencenr>0</bt_sequencenr><dr_name></dr_name><dr_surgeryaddress></dr_surgeryaddress><dr_practiceemail></dr_practiceemail><dr_surname></dr_surname><dr_title></dr_title><dr_practicenumber></dr_practicenumber><dr_practiceipanumber></dr_practiceipanumber><dr_practicetelephone></dr_practicetelephone></B2><B4 /><B5><drtemplate_code></drtemplate_code><drtemplate_flags>00000000000000000000000000000000000</drtemplate_flags><drtemplate_enddate>1899-12-31</drtemplate_enddate><drtemplate_startdate>1899-12-31</drtemplate_startdate><drtemplate_practicenumber></drtemplate_practicenumber></B5><E6 /><NonMemMap><card_claimingreason></card_claimingreason><card_reterrors>False</card_reterrors><switch_integrated>False</switch_integrated><supervisor_password></supervisor_password><card_claimfilesloading>False</card_claimfilesloading><card_retcompleted>True</card_retcompleted><card_claimingpossible>True</card_claimingpossible><code_file_version>30</code_file_version><medicalaid_scheme>NULL</medicalaid_scheme><btupdate_completed>False</btupdate_completed><patient_hospitalnumber>11007503</patient_hospitalnumber><virtualcard>False</virtualcard></NonMemMap><RepeatableVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>10</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination></RepeatableVaccinations><B6><Message><Nr>1</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>2</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>3</Nr><Date>1899-12-31</Date><Text></Text></Message></B6><Scripts><Script><Nr>1</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-01</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>2</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-01</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>3</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-01</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script></Scripts><Benefits><Benefit><Nr>1</Nr><Description>OUT PATIENT OVERALL</Description><Amount>293203.99</Amount><PreAuthNeeded>False</PreAuthNeeded><Claimable>True</Claimable></Benefit></Benefits><OnceOffVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name>Birth-BCG &amp; Polio</Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name>6w-DTacP-Hib, DPT</Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name>10w-DPT,Polio,H Influenza,Hepatitis B</Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name>14w-DPT,Polio,H Influenza &amp; Hepatitis B</Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name>9m-Measles</Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-Measles</Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-MMR</Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name>18m-DPT,Polio,H Influenza,Hep A</Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name>5yr-DT,Polio &amp; MMR</Name></Vaccination></OnceOffVaccinations></AdmissionInformation>', 'Exchange_Date' => '2015-10-30 07:05:02', 'Exchange_File' => '<Claim>
			<Claim_Header>
				<Invoice_Number>PDRC140646421</Invoice_Number>
				<Claim_Date>2015-10-30</Claim_Date>
				<Claim_Time>07:05:39</Claim_Time>
				<Pool_Number>1</Pool_Number>
				<Total_Services>0</Total_Services>
				<Gross_Amount>3993</Gross_Amount>
				<Provider>
				<Role>SP</Role>
				<Country_Code>KEN</Country_Code>
				<Group_Practice_Number>SKSP_92</Group_Practice_Number>
				<Group_Practice_Name>The Mater Hospital</Group_Practice_Name>
				</Provider>
				<Authorization>
				<Pre_Authorization_Number>0</Pre_Authorization_Number>
				<Pre_Authorization_Amount>0</Pre_Authorization_Amount>
				</Authorization>
				<Payment_Modifiers>
					<Payment_Modifier>
						<Type>1</Type>
						<Amount>0</Amount>
						<Receipt>0</Receipt>
					</Payment_Modifier>
					<PaymentModifier>
						<Type>5</Type>
						<NHIF_Member_Nr>0</NHIF_Member_Nr>
						<NHIF_Contributor_Nr>0</NHIF_Contributor_Nr>
						<NHIF_Employer_Code>0</NHIF_Employer_Code>
						<NHIF_Site_Nr>0</NHIF_Site_Nr>
						<NHIF_Patient_Relation>0</NHIF_Patient_Relation>
						<Diagnosis_Code>0</Diagnosis_Code>
						<Admit_Date>2015-10-30</Admit_Date>
						<Discharge_Date>2015-10-30</Discharge_Date>
						<Days_Used>0</Days_Used>
						<Amount>0</Amount>
					</PaymentModifier>
				</Payment_Modifiers>
			</Claim_Header>
			<Member>
				<Membership_Number>8761108-04</Membership_Number>
				<card_serialnumber>000000100006DA3C</card_serialnumber>
				<Scheme_Code>unknown</Scheme_Code>
				<Scheme_Plan>unknown</Scheme_Plan>
			</Member>
			<Patient>
				<Dependant>Y</Dependant>
				<First_Name>RODNEY</First_Name>
				<Middle_Name>KIMUTAI</Middle_Name>
				<Surname>KUTTO</Surname>
				<Date_Of_Birth>2005-12-02</Date_Of_Birth>
				<Gender>M</Gender>
			</Patient>
			<Claim_Data>
				<Discharge_Notes>Diagn</Discharge_Notes><Service>
							<Number>1</Number>
							<Invoice_Number>PDRC140646421</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-30</Start_Date>
							<Start_Time>07:05:39</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Medication</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>C039</Code>
							<Code_Description>CIPROBAY 250MG TABLETS</Code_Description>
							<Quantity>10</Quantity>
							<Total_Amount>2074.8</Total_Amount>
							<Reason></Reason>
						</Service><Service>
							<Number>2</Number>
							<Invoice_Number>PDRC140646421</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-30</Start_Date>
							<Start_Time>07:05:39</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Medication</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>F114</Code>
							<Code_Description>FLORANORM SATCHET</Code_Description>
							<Quantity>10</Quantity>
							<Total_Amount>949.4</Total_Amount>
							<Reason></Reason>
						</Service><Service>
							<Number>3</Number>
							<Invoice_Number>PDRC140646421</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-30</Start_Date>
							<Start_Time>07:05:39</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Medication</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>S126</Code>
							<Code_Description>SEVEN-SEAS COD LIVER OIL 170</Code_Description>
							<Quantity>1</Quantity>
							<Total_Amount>967.83</Total_Amount>
							<Reason></Reason>
						</Service></Claim_Data>
			</Claim>', 'Result_Date' => '0000-00-00 00:00:00', 'Result_File' => ''],
            ['Global_ID' => 'KE000000000000000000000000001351257', 'Member_Nr' => '15051914', 'Admit_ID' => '745265', 'Progress_Flag' => '0', 'Rejection_Reason' => NULL, 'Exchange_Type' => '1', 'InOut_Type' => '1', 'Location_ID' => '1', 'Smart_Date' => '2015-10-29 09:31:40', 'Smart_File' => '<AdmissionInformation><Admit_Notes></Admit_Notes><PaymentModifiers><PaymentModifier><Type>0</Type><Amount_Required>0</Amount_Required><Receipt></Receipt></PaymentModifier><PaymentModifier><Type>5</Type><NHIF_Member_Nr>ACTIVE</NHIF_Member_Nr><NHIF_Contributor_Nr></NHIF_Contributor_Nr><NHIF_Employer_Code></NHIF_Employer_Code><NHIF_Site_Nr>0</NHIF_Site_Nr><NHIF_Patient_Relation>Self</NHIF_Patient_Relation><Diagnosis_Code></Diagnosis_Code><Admit_Date>10/29/2015 9:41:38 AM</Admit_Date><Discharge_Date></Discharge_Date><Days_Used></Days_Used><Amount></Amount></PaymentModifier></PaymentModifiers><A1><card_retmasscounter>1</card_retmasscounter><card_issuedate>2015-09-26</card_issuedate><card_issuername>SMART KENYA</card_issuername><card_serialnumber>000000100015550B</card_serialnumber><card_validitystatus>1</card_validitystatus><card_retcounter>1</card_retcounter></A1><A2><patient_marriagestatus></patient_marriagestatus><policy_country>KE</policy_country><patient_surname>MUNIKAH</patient_surname><patient_partnerprevioussurname></patient_partnerprevioussurname><patient_previoussurname></patient_previoussurname><patient_marriagedate>1899-12-31</patient_marriagedate><patient_partnerdob>1899-12-31</patient_partnerdob><patient_forenames>JAMES SIMON  MUNIKAH</patient_forenames><patient_dob>1970-01-01</patient_dob><patient_title></patient_title><policy_currency>404</policy_currency><policy_id>5488</policy_id><patient_language></patient_language></A2><A3><patient_address></patient_address><employer_fax></employer_fax><employer_cellphone></employer_cellphone><employer_telephone></employer_telephone><patient_cellphone></patient_cellphone><patient_email></patient_email><employer_name></employer_name><employer_address>RESOLUTION INDIVIDUAL</employer_address><employer_department>0000</employer_department><patient_telephone></patient_telephone></A3><A4><patient_id>7129988</patient_id><patient_birthcountry></patient_birthcountry><patient_passportnumber>130664</patient_passportnumber><patient_division></patient_division><patient_location></patient_location><patient_birthprovince></patient_birthprovince><patient_idissuedate>1899-12-31</patient_idissuedate><patient_passportexpirydate>1899-12-31</patient_passportexpirydate><patient_birthcity></patient_birthcity><patient_subdivision></patient_subdivision><patient_idcountry></patient_idcountry><patient_passportapplicationdate>1899-12-31</patient_passportapplicationdate><patient_passportcountry></patient_passportcountry><patient_passportissuedate>1899-12-31</patient_passportissuedate><patient_passportcity></patient_passportcity><patient_sublocation></patient_sublocation></A4><A5><patient_gender>1</patient_gender><patient_minutia_identifier>0</patient_minutia_identifier><patient_height>0</patient_height></A5><A6><patient_nextofkin></patient_nextofkin><patient_nextofkin_nr></patient_nextofkin_nr><patient_organdonor>False</patient_organdonor><patient_livingwill>False</patient_livingwill><patient_allergies></patient_allergies><patient_bloodtype></patient_bloodtype><patient_chronicmedication></patient_chronicmedication><patient_chronicconditions></patient_chronicconditions></A6><A7 /><A8><patient_riskfactors></patient_riskfactors></A8><B1><medicalaid_expiry>2016-09-14</medicalaid_expiry><medicalaid_rules>0</medicalaid_rules><medicalaid_showpools>True</medicalaid_showpools><medicalaid_plan>I100D20O20PR</medicalaid_plan><medicalaid_limit>0</medicalaid_limit><medicalaid_number>RIL130664-00</medicalaid_number><medicalaid_groupstatus></medicalaid_groupstatus><nhif_membernumber>ACTIVE</nhif_membernumber><medicalaid_regdate>2015-09-15</medicalaid_regdate><global_id>KE000000000000000000000000001351257</global_id><medicalaid_code>RI</medicalaid_code><dependant_number>00</dependant_number></B1><B2><bt_sequencenr>0</bt_sequencenr><dr_name></dr_name><dr_surgeryaddress></dr_surgeryaddress><dr_practiceemail></dr_practiceemail><dr_surname></dr_surname><dr_title></dr_title><dr_practicenumber></dr_practicenumber><dr_practiceipanumber></dr_practiceipanumber><dr_practicetelephone></dr_practicetelephone></B2><B4 /><B5><drtemplate_code></drtemplate_code><drtemplate_flags>00000000000000000000000000000000000</drtemplate_flags><drtemplate_enddate>1899-12-31</drtemplate_enddate><drtemplate_startdate>1899-12-31</drtemplate_startdate><drtemplate_practicenumber></drtemplate_practicenumber></B5><E6 /><NonMemMap><card_claimingreason></card_claimingreason><card_reterrors>False</card_reterrors><switch_integrated>False</switch_integrated><supervisor_password></supervisor_password><card_claimfilesloading>False</card_claimfilesloading><card_retcompleted>True</card_retcompleted><card_claimingpossible>True</card_claimingpossible><code_file_version>30</code_file_version><medicalaid_scheme>NULL</medicalaid_scheme><btupdate_completed>False</btupdate_completed><patient_hospitalnumber>15051914</patient_hospitalnumber><virtualcard>False</virtualcard></NonMemMap><RepeatableVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>10</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination></RepeatableVaccinations><B6><Message><Nr>1</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>2</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>3</Nr><Date>1899-12-31</Date><Text></Text></Message></B6><Scripts><Script><Nr>1</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>2</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>3</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script></Scripts><Benefits><Benefit><Nr>1</Nr><Description>OUT PATIENT OVERALL (CO-PAY APPLICABLE)</Description><Amount>100000.00</Amount><PreAuthNeeded>False</PreAuthNeeded><Claimable>True</Claimable></Benefit></Benefits><OnceOffVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name>Birth-BCG &amp; Polio</Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name>6w-DTacP-Hib, DPT</Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name>10w-DPT,Polio,H Influenza,Hepatitis B</Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name>14w-DPT,Polio,H Influenza &amp; Hepatitis B</Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name>9m-Measles</Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-Measles</Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-MMR</Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name>18m-DPT,Polio,H Influenza,Hep A</Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name>5yr-DT,Polio &amp; MMR</Name></Vaccination></OnceOffVaccinations></AdmissionInformation>', 'Exchange_Date' => '2015-10-29 09:31:46', 'Exchange_File' => '<Claim>
			<Claim_Header>
				<Invoice_Number>OSLO02280215</Invoice_Number>
				<Claim_Date>2015-10-29</Claim_Date>
				<Claim_Time>09:32:24</Claim_Time>
				<Pool_Number>1</Pool_Number>
				<Total_Services>1</Total_Services>
				<Gross_Amount>1600</Gross_Amount>
				<Provider>
				<Role>SP</Role>
				<Country_Code>KEN</Country_Code>
				<Group_Practice_Number>SKSP_92</Group_Practice_Number>
				<Group_Practice_Name>The Mater Hospital</Group_Practice_Name>
				</Provider>
				<Authorization>
				<Pre_Authorization_Number>0</Pre_Authorization_Number>
				<Pre_Authorization_Amount>0</Pre_Authorization_Amount>
				</Authorization>
				<Payment_Modifiers>
					<Payment_Modifier>
						<Type>1</Type>
						<Amount>0</Amount>
						<Receipt>0</Receipt>
					</Payment_Modifier>
					<PaymentModifier>
						<Type>5</Type>
						<NHIF_Member_Nr>0</NHIF_Member_Nr>
						<NHIF_Contributor_Nr>0</NHIF_Contributor_Nr>
						<NHIF_Employer_Code>0</NHIF_Employer_Code>
						<NHIF_Site_Nr>0</NHIF_Site_Nr>
						<NHIF_Patient_Relation>0</NHIF_Patient_Relation>
						<Diagnosis_Code>0</Diagnosis_Code>
						<Admit_Date>2015-10-29</Admit_Date>
						<Discharge_Date>2015-10-29</Discharge_Date>
						<Days_Used>0</Days_Used>
						<Amount>0</Amount>
					</PaymentModifier>
				</Payment_Modifiers>
			</Claim_Header>
			<Member>
				<Membership_Number>130664</Membership_Number>
				<card_serialnumber>000000100015550B</card_serialnumber>
				<Scheme_Code>unknown</Scheme_Code>
				<Scheme_Plan>unknown</Scheme_Plan>
			</Member>
			<Patient>
				<Dependant>Y</Dependant>
				<First_Name>JAMES</First_Name>
				<Middle_Name>SIMON</Middle_Name>
				<Surname>MUNIKAH</Surname>
				<Date_Of_Birth>1966-11-24</Date_Of_Birth>
				<Gender>M</Gender>
			</Patient>
			<Claim_Data>
				<Discharge_Notes>Diagn</Discharge_Notes><Service>
							<Number>1</Number>
							<Invoice_Number>OSLO02280215</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-29</Start_Date>
							<Start_Time>09:32:24</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Consultation</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>CONS</Code>
							<Code_Description>CONSULTATION  FEE</Code_Description>
							<Quantity>1</Quantity>
							<Total_Amount>1600.00</Total_Amount>
							<Reason></Reason>
						</Service><Service>
							<Number>2</Number>
							<Invoice_Number>OSLO02280215</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-29</Start_Date>
							<Start_Time>09:32:24</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Consultation</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>CONS</Code>
							<Code_Description>CONSULTATION  FEE</Code_Description>
							<Quantity>1</Quantity>
							<Total_Amount>-200</Total_Amount>
							<Reason></Reason>
						</Service></Claim_Data>
			</Claim>', 'Result_Date' => '0000-00-00 00:00:00', 'Result_File' => ''],
            ['Global_ID' => 'KE000000000000000000000000001351257', 'Member_Nr' => '15051914', 'Admit_ID' => '745265', 'Progress_Flag' => '0', 'Rejection_Reason' => NULL, 'Exchange_Type' => '1', 'InOut_Type' => '1', 'Location_ID' => '2', 'Smart_Date' => '2015-10-29 09:55:32', 'Smart_File' => '<AdmissionInformation><Admit_Notes></Admit_Notes><PaymentModifiers><PaymentModifier><Type>0</Type><Amount_Required>0</Amount_Required><Receipt></Receipt></PaymentModifier><PaymentModifier><Type>5</Type><NHIF_Member_Nr>ACTIVE</NHIF_Member_Nr><NHIF_Contributor_Nr></NHIF_Contributor_Nr><NHIF_Employer_Code></NHIF_Employer_Code><NHIF_Site_Nr>0</NHIF_Site_Nr><NHIF_Patient_Relation>Self</NHIF_Patient_Relation><Diagnosis_Code></Diagnosis_Code><Admit_Date>10/29/2015 9:41:38 AM</Admit_Date><Discharge_Date></Discharge_Date><Days_Used></Days_Used><Amount></Amount></PaymentModifier></PaymentModifiers><A1><card_retmasscounter>1</card_retmasscounter><card_issuedate>2015-09-26</card_issuedate><card_issuername>SMART KENYA</card_issuername><card_serialnumber>000000100015550B</card_serialnumber><card_validitystatus>1</card_validitystatus><card_retcounter>1</card_retcounter></A1><A2><patient_marriagestatus></patient_marriagestatus><policy_country>KE</policy_country><patient_surname>MUNIKAH</patient_surname><patient_partnerprevioussurname></patient_partnerprevioussurname><patient_previoussurname></patient_previoussurname><patient_marriagedate>1899-12-31</patient_marriagedate><patient_partnerdob>1899-12-31</patient_partnerdob><patient_forenames>JAMES SIMON  MUNIKAH</patient_forenames><patient_dob>1970-01-01</patient_dob><patient_title></patient_title><policy_currency>404</policy_currency><policy_id>5488</policy_id><patient_language></patient_language></A2><A3><patient_address></patient_address><employer_fax></employer_fax><employer_cellphone></employer_cellphone><employer_telephone></employer_telephone><patient_cellphone></patient_cellphone><patient_email></patient_email><employer_name></employer_name><employer_address>RESOLUTION INDIVIDUAL</employer_address><employer_department>0000</employer_department><patient_telephone></patient_telephone></A3><A4><patient_id>7129988</patient_id><patient_birthcountry></patient_birthcountry><patient_passportnumber>130664</patient_passportnumber><patient_division></patient_division><patient_location></patient_location><patient_birthprovince></patient_birthprovince><patient_idissuedate>1899-12-31</patient_idissuedate><patient_passportexpirydate>1899-12-31</patient_passportexpirydate><patient_birthcity></patient_birthcity><patient_subdivision></patient_subdivision><patient_idcountry></patient_idcountry><patient_passportapplicationdate>1899-12-31</patient_passportapplicationdate><patient_passportcountry></patient_passportcountry><patient_passportissuedate>1899-12-31</patient_passportissuedate><patient_passportcity></patient_passportcity><patient_sublocation></patient_sublocation></A4><A5><patient_gender>1</patient_gender><patient_minutia_identifier>0</patient_minutia_identifier><patient_height>0</patient_height></A5><A6><patient_nextofkin></patient_nextofkin><patient_nextofkin_nr></patient_nextofkin_nr><patient_organdonor>False</patient_organdonor><patient_livingwill>False</patient_livingwill><patient_allergies></patient_allergies><patient_bloodtype></patient_bloodtype><patient_chronicmedication></patient_chronicmedication><patient_chronicconditions></patient_chronicconditions></A6><A7 /><A8><patient_riskfactors></patient_riskfactors></A8><B1><medicalaid_expiry>2016-09-14</medicalaid_expiry><medicalaid_rules>0</medicalaid_rules><medicalaid_showpools>True</medicalaid_showpools><medicalaid_plan>I100D20O20PR</medicalaid_plan><medicalaid_limit>0</medicalaid_limit><medicalaid_number>RIL130664-00</medicalaid_number><medicalaid_groupstatus></medicalaid_groupstatus><nhif_membernumber>ACTIVE</nhif_membernumber><medicalaid_regdate>2015-09-15</medicalaid_regdate><global_id>KE000000000000000000000000001351257</global_id><medicalaid_code>RI</medicalaid_code><dependant_number>00</dependant_number></B1><B2><bt_sequencenr>0</bt_sequencenr><dr_name></dr_name><dr_surgeryaddress></dr_surgeryaddress><dr_practiceemail></dr_practiceemail><dr_surname></dr_surname><dr_title></dr_title><dr_practicenumber></dr_practicenumber><dr_practiceipanumber></dr_practiceipanumber><dr_practicetelephone></dr_practicetelephone></B2><B4 /><B5><drtemplate_code></drtemplate_code><drtemplate_flags>00000000000000000000000000000000000</drtemplate_flags><drtemplate_enddate>1899-12-31</drtemplate_enddate><drtemplate_startdate>1899-12-31</drtemplate_startdate><drtemplate_practicenumber></drtemplate_practicenumber></B5><E6 /><NonMemMap><card_claimingreason></card_claimingreason><card_reterrors>False</card_reterrors><switch_integrated>False</switch_integrated><supervisor_password></supervisor_password><card_claimfilesloading>False</card_claimfilesloading><card_retcompleted>True</card_retcompleted><card_claimingpossible>True</card_claimingpossible><code_file_version>30</code_file_version><medicalaid_scheme>NULL</medicalaid_scheme><btupdate_completed>False</btupdate_completed><patient_hospitalnumber>15051914</patient_hospitalnumber><virtualcard>False</virtualcard></NonMemMap><RepeatableVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>10</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination></RepeatableVaccinations><B6><Message><Nr>1</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>2</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>3</Nr><Date>1899-12-31</Date><Text></Text></Message></B6><Scripts><Script><Nr>1</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>2</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>3</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script></Scripts><Benefits><Benefit><Nr>1</Nr><Description>OUT PATIENT OVERALL (CO-PAY APPLICABLE)</Description><Amount>98600.00</Amount><PreAuthNeeded>False</PreAuthNeeded><Claimable>True</Claimable></Benefit></Benefits><OnceOffVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name>Birth-BCG &amp; Polio</Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name>6w-DTacP-Hib, DPT</Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name>10w-DPT,Polio,H Influenza,Hepatitis B</Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name>14w-DPT,Polio,H Influenza &amp; Hepatitis B</Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name>9m-Measles</Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-Measles</Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-MMR</Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name>18m-DPT,Polio,H Influenza,Hep A</Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name>5yr-DT,Polio &amp; MMR</Name></Vaccination></OnceOffVaccinations></AdmissionInformation>', 'Exchange_Date' => '2015-10-29 09:56:20', 'Exchange_File' => '<Claim>
			<Claim_Header>
				<Invoice_Number>PDRC140646140</Invoice_Number>
				<Claim_Date>2015-10-29</Claim_Date>
				<Claim_Time>09:56:57</Claim_Time>
				<Pool_Number>1</Pool_Number>
				<Total_Services>0</Total_Services>
				<Gross_Amount>800</Gross_Amount>
				<Provider>
				<Role>SP</Role>
				<Country_Code>KEN</Country_Code>
				<Group_Practice_Number>SKSP_92</Group_Practice_Number>
				<Group_Practice_Name>The Mater Hospital</Group_Practice_Name>
				</Provider>
				<Authorization>
				<Pre_Authorization_Number>0</Pre_Authorization_Number>
				<Pre_Authorization_Amount>0</Pre_Authorization_Amount>
				</Authorization>
				<Payment_Modifiers>
					<Payment_Modifier>
						<Type>1</Type>
						<Amount>0</Amount>
						<Receipt>0</Receipt>
					</Payment_Modifier>
					<PaymentModifier>
						<Type>5</Type>
						<NHIF_Member_Nr>0</NHIF_Member_Nr>
						<NHIF_Contributor_Nr>0</NHIF_Contributor_Nr>
						<NHIF_Employer_Code>0</NHIF_Employer_Code>
						<NHIF_Site_Nr>0</NHIF_Site_Nr>
						<NHIF_Patient_Relation>0</NHIF_Patient_Relation>
						<Diagnosis_Code>0</Diagnosis_Code>
						<Admit_Date>2015-10-29</Admit_Date>
						<Discharge_Date>2015-10-29</Discharge_Date>
						<Days_Used>0</Days_Used>
						<Amount>0</Amount>
					</PaymentModifier>
				</Payment_Modifiers>
			</Claim_Header>
			<Member>
				<Membership_Number>130664</Membership_Number>
				<card_serialnumber>000000100015550B</card_serialnumber>
				<Scheme_Code>unknown</Scheme_Code>
				<Scheme_Plan>unknown</Scheme_Plan>
			</Member>
			<Patient>
				<Dependant>Y</Dependant>
				<First_Name>JAMES</First_Name>
				<Middle_Name>SIMON</Middle_Name>
				<Surname>MUNIKAH</Surname>
				<Date_Of_Birth>1966-11-24</Date_Of_Birth>
				<Gender>M</Gender>
			</Patient>
			<Claim_Data>
				<Discharge_Notes>Diagn</Discharge_Notes><Service>
							<Number>1</Number>
							<Invoice_Number>PDRC140646140</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-29</Start_Date>
							<Start_Time>09:56:57</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Medication</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>F065</Code>
							<Code_Description>KETESSE 25MG CAPSULES</Code_Description>
							<Quantity>20</Quantity>
							<Total_Amount>776.8</Total_Amount>
							<Reason></Reason>
						</Service><Service>
							<Number>2</Number>
							<Invoice_Number>PDRC140646140</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-29</Start_Date>
							<Start_Time>09:56:57</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Medication</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>G098</Code>
							<Code_Description>GENTAMYCIN EYE/EAR DROPS</Code_Description>
							<Quantity>1</Quantity>
							<Total_Amount>22.97</Total_Amount>
							<Reason></Reason>
						</Service></Claim_Data>
			</Claim>', 'Result_Date' => '0000-00-00 00:00:00', 'Result_File' => ''],
            ['Global_ID' => 'KE000000000000000000000000001351257', 'Member_Nr' => '15051914', 'Admit_ID' => '745265', 'Progress_Flag' => '0', 'Rejection_Reason' => NULL, 'Exchange_Type' => '1', 'InOut_Type' => '1', 'Location_ID' => '1', 'Smart_Date' => '2015-10-29 10:54:32', 'Smart_File' => '<AdmissionInformation><Admit_Notes></Admit_Notes><PaymentModifiers><PaymentModifier><Type>0</Type><Amount_Required>0</Amount_Required><Receipt></Receipt></PaymentModifier><PaymentModifier><Type>5</Type><NHIF_Member_Nr>ACTIVE</NHIF_Member_Nr><NHIF_Contributor_Nr></NHIF_Contributor_Nr><NHIF_Employer_Code></NHIF_Employer_Code><NHIF_Site_Nr>0</NHIF_Site_Nr><NHIF_Patient_Relation>Self</NHIF_Patient_Relation><Diagnosis_Code></Diagnosis_Code><Admit_Date>10/29/2015 9:41:38 AM</Admit_Date><Discharge_Date></Discharge_Date><Days_Used></Days_Used><Amount></Amount></PaymentModifier></PaymentModifiers><A1><card_retmasscounter>1</card_retmasscounter><card_issuedate>2015-09-26</card_issuedate><card_issuername>SMART KENYA</card_issuername><card_serialnumber>000000100015550B</card_serialnumber><card_validitystatus>1</card_validitystatus><card_retcounter>1</card_retcounter></A1><A2><patient_marriagestatus></patient_marriagestatus><policy_country>KE</policy_country><patient_surname>MUNIKAH</patient_surname><patient_partnerprevioussurname></patient_partnerprevioussurname><patient_previoussurname></patient_previoussurname><patient_marriagedate>1899-12-31</patient_marriagedate><patient_partnerdob>1899-12-31</patient_partnerdob><patient_forenames>JAMES SIMON  MUNIKAH</patient_forenames><patient_dob>1970-01-01</patient_dob><patient_title></patient_title><policy_currency>404</policy_currency><policy_id>5488</policy_id><patient_language></patient_language></A2><A3><patient_address></patient_address><employer_fax></employer_fax><employer_cellphone></employer_cellphone><employer_telephone></employer_telephone><patient_cellphone></patient_cellphone><patient_email></patient_email><employer_name></employer_name><employer_address>RESOLUTION INDIVIDUAL</employer_address><employer_department>0000</employer_department><patient_telephone></patient_telephone></A3><A4><patient_id>7129988</patient_id><patient_birthcountry></patient_birthcountry><patient_passportnumber>130664</patient_passportnumber><patient_division></patient_division><patient_location></patient_location><patient_birthprovince></patient_birthprovince><patient_idissuedate>1899-12-31</patient_idissuedate><patient_passportexpirydate>1899-12-31</patient_passportexpirydate><patient_birthcity></patient_birthcity><patient_subdivision></patient_subdivision><patient_idcountry></patient_idcountry><patient_passportapplicationdate>1899-12-31</patient_passportapplicationdate><patient_passportcountry></patient_passportcountry><patient_passportissuedate>1899-12-31</patient_passportissuedate><patient_passportcity></patient_passportcity><patient_sublocation></patient_sublocation></A4><A5><patient_gender>1</patient_gender><patient_minutia_identifier>0</patient_minutia_identifier><patient_height>0</patient_height></A5><A6><patient_nextofkin></patient_nextofkin><patient_nextofkin_nr></patient_nextofkin_nr><patient_organdonor>False</patient_organdonor><patient_livingwill>False</patient_livingwill><patient_allergies></patient_allergies><patient_bloodtype></patient_bloodtype><patient_chronicmedication></patient_chronicmedication><patient_chronicconditions></patient_chronicconditions></A6><A7 /><A8><patient_riskfactors></patient_riskfactors></A8><B1><medicalaid_expiry>2016-09-14</medicalaid_expiry><medicalaid_rules>0</medicalaid_rules><medicalaid_showpools>True</medicalaid_showpools><medicalaid_plan>I100D20O20PR</medicalaid_plan><medicalaid_limit>0</medicalaid_limit><medicalaid_number>RIL130664-00</medicalaid_number><medicalaid_groupstatus></medicalaid_groupstatus><nhif_membernumber>ACTIVE</nhif_membernumber><medicalaid_regdate>2015-09-15</medicalaid_regdate><global_id>KE000000000000000000000000001351257</global_id><medicalaid_code>RI</medicalaid_code><dependant_number>00</dependant_number></B1><B2><bt_sequencenr>0</bt_sequencenr><dr_name></dr_name><dr_surgeryaddress></dr_surgeryaddress><dr_practiceemail></dr_practiceemail><dr_surname></dr_surname><dr_title></dr_title><dr_practicenumber></dr_practicenumber><dr_practiceipanumber></dr_practiceipanumber><dr_practicetelephone></dr_practicetelephone></B2><B4 /><B5><drtemplate_code></drtemplate_code><drtemplate_flags>00000000000000000000000000000000000</drtemplate_flags><drtemplate_enddate>1899-12-31</drtemplate_enddate><drtemplate_startdate>1899-12-31</drtemplate_startdate><drtemplate_practicenumber></drtemplate_practicenumber></B5><E6 /><NonMemMap><card_claimingreason></card_claimingreason><card_reterrors>False</card_reterrors><switch_integrated>False</switch_integrated><supervisor_password></supervisor_password><card_claimfilesloading>False</card_claimfilesloading><card_retcompleted>True</card_retcompleted><card_claimingpossible>True</card_claimingpossible><code_file_version>30</code_file_version><medicalaid_scheme>NULL</medicalaid_scheme><btupdate_completed>False</btupdate_completed><patient_hospitalnumber>15051914</patient_hospitalnumber><virtualcard>False</virtualcard></NonMemMap><RepeatableVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination><Vaccination><Nr>10</Nr><Date>1899-12-31</Date><Provider></Provider><Name></Name></Vaccination></RepeatableVaccinations><B6><Message><Nr>1</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>2</Nr><Date>1899-12-31</Date><Text></Text></Message><Message><Nr>3</Nr><Date>1899-12-31</Date><Text></Text></Message></B6><Scripts><Script><Nr>1</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>2</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script><Script><Nr>3</Nr><Type>0</Type><Date>1899-12-31</Date><Expiry>1899-12-31</Expiry><Provider></Provider><Issuer></Issuer><AccountNrPart1></AccountNrPart1><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line><Line><VoucherNumber></VoucherNumber><Diagnosis></Diagnosis><NappiCode></NappiCode><Quantity>0</Quantity><Repeats>0</Repeats></Line></Script></Scripts><Benefits><Benefit><Nr>2</Nr><Description>OUT PATIENT DENTAL</Description><Amount>20000.00</Amount><PreAuthNeeded>False</PreAuthNeeded><Claimable>True</Claimable></Benefit></Benefits><OnceOffVaccinations IssuerProtected="No"><Vaccination><Nr>1</Nr><Date>1899-12-31</Date><Provider></Provider><Name>Birth-BCG &amp; Polio</Name></Vaccination><Vaccination><Nr>2</Nr><Date>1899-12-31</Date><Provider></Provider><Name>6w-DTacP-Hib, DPT</Name></Vaccination><Vaccination><Nr>3</Nr><Date>1899-12-31</Date><Provider></Provider><Name>10w-DPT,Polio,H Influenza,Hepatitis B</Name></Vaccination><Vaccination><Nr>4</Nr><Date>1899-12-31</Date><Provider></Provider><Name>14w-DPT,Polio,H Influenza &amp; Hepatitis B</Name></Vaccination><Vaccination><Nr>5</Nr><Date>1899-12-31</Date><Provider></Provider><Name>9m-Measles</Name></Vaccination><Vaccination><Nr>6</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-Measles</Name></Vaccination><Vaccination><Nr>7</Nr><Date>1899-12-31</Date><Provider></Provider><Name>15m-MMR</Name></Vaccination><Vaccination><Nr>8</Nr><Date>1899-12-31</Date><Provider></Provider><Name>18m-DPT,Polio,H Influenza,Hep A</Name></Vaccination><Vaccination><Nr>9</Nr><Date>1899-12-31</Date><Provider></Provider><Name>5yr-DT,Polio &amp; MMR</Name></Vaccination></OnceOffVaccinations></AdmissionInformation>', 'Exchange_Date' => '2015-10-29 11:02:45', 'Exchange_File' => '<Claim>
			<Claim_Header>
				<Invoice_Number>JDRA140404625</Invoice_Number>
				<Claim_Date>2015-10-29</Claim_Date>
				<Claim_Time>11:03:22</Claim_Time>
				<Pool_Number>2</Pool_Number>
				<Total_Services>0</Total_Services>
				<Gross_Amount>1600</Gross_Amount>
				<Provider>
				<Role>SP</Role>
				<Country_Code>KEN</Country_Code>
				<Group_Practice_Number>SKSP_92</Group_Practice_Number>
				<Group_Practice_Name>The Mater Hospital</Group_Practice_Name>
				</Provider>
				<Authorization>
				<Pre_Authorization_Number>0</Pre_Authorization_Number>
				<Pre_Authorization_Amount>0</Pre_Authorization_Amount>
				</Authorization>
				<Payment_Modifiers>
					<Payment_Modifier>
						<Type>1</Type>
						<Amount>0</Amount>
						<Receipt>0</Receipt>
					</Payment_Modifier>
					<PaymentModifier>
						<Type>5</Type>
						<NHIF_Member_Nr>0</NHIF_Member_Nr>
						<NHIF_Contributor_Nr>0</NHIF_Contributor_Nr>
						<NHIF_Employer_Code>0</NHIF_Employer_Code>
						<NHIF_Site_Nr>0</NHIF_Site_Nr>
						<NHIF_Patient_Relation>0</NHIF_Patient_Relation>
						<Diagnosis_Code>0</Diagnosis_Code>
						<Admit_Date>2015-10-29</Admit_Date>
						<Discharge_Date>2015-10-29</Discharge_Date>
						<Days_Used>0</Days_Used>
						<Amount>0</Amount>
					</PaymentModifier>
				</Payment_Modifiers>
			</Claim_Header>
			<Member>
				<Membership_Number>130664</Membership_Number>
				<card_serialnumber>000000100015550B</card_serialnumber>
				<Scheme_Code>unknown</Scheme_Code>
				<Scheme_Plan>unknown</Scheme_Plan>
			</Member>
			<Patient>
				<Dependant>Y</Dependant>
				<First_Name>JAMES</First_Name>
				<Middle_Name>SIMON</Middle_Name>
				<Surname>MUNIKAH</Surname>
				<Date_Of_Birth>1966-11-24</Date_Of_Birth>
				<Gender>M</Gender>
			</Patient>
			<Claim_Data>
				<Discharge_Notes>Diagn</Discharge_Notes><Service>
							<Number>1</Number>
							<Invoice_Number>JDRA140404625</Invoice_Number>
							<Global_Invoice_Nr>0</Global_Invoice_Nr> 
							<Start_Date>2015-10-29</Start_Date>
							<Start_Time>11:03:22</Start_Time>
							<Provider>
								<Role>SP</Role>
								<Practice_Number>SKSP_92</Practice_Number>
							</Provider>
							<Diagnosis>
								<Stage>P</Stage>
								<Code_Type>ICD10</Code_Type>
								<Code>UNKN</Code>
							</Diagnosis>
							<Encounter_Type>Procedure</Encounter_Type>
							<Code_Type>Mcode</Code_Type>
							<Code>AED001</Code>
							<Code_Description>CONSULTATION</Code_Description>
							<Quantity>1</Quantity>
							<Total_Amount>1600</Total_Amount>
							<Reason></Reason>
						</Service></Claim_Data>
			</Claim>', 'Result_Date' => '0000-00-00 00:00:00', 'Result_File' => '']
        ];

    }
}
